<script setup>
import { BadgeCheck, Blocks, Check, Cpu, Gauge, MonitorCog, Settings, Webcam } from 'lucide-vue-next'
const stages=[
 {icon:Cpu,title:'阶段1：吃透 U-boot（6周）',tag:'从“懂皮毛”到“多芯片移植高手”',items:['拆解u-boot代码框架','多款芯片移植实操','吃透启动流程、芯片架构','全程随时技术支持']},
 {icon:Blocks,title:'阶段2：夯实 Linux驱动基础（4周）',tag:'从“会看”到“能独立编写”',items:['结合视频打基础','多款开发板动手编写','全流程实操随时答疑','独立完成驱动编写']},
 {icon:Webcam,title:'阶段3：攻克复杂驱动子系统（6周）',tag:'练出“原厂级”驱动开发能力',items:['吃透驱动底层逻辑','基于寄存器实现I2C/SPI','摄像头、声卡等大驱动','全程把关，练一个会一个']},
 {icon:Settings,title:'阶段4：深挖 Linux内核核心（6周）',tag:'从“用内核”到“懂内核”',items:['量身定制学习任务','解决进程/内存管理疑难','深入拆解内核机制','提高调试技能']},
 {icon:MonitorCog,title:'阶段5：精通 Linux系统构建（4周）',tag:'从“会用系统”到“能造系统”',items:['busybox手工构建','buildroot构建系统','Ubuntu系统构建','对标企业资深工程师']}
]
</script>
<template><div class="route-c-shell">
  <header class="intro"><div class="person">🎓<span>应届生学员C（Linux驱动/BSP）</span></div><div class="pain"><b>你的痛点我秒懂，目标我来帮你落地！</b><p>你的基础：略懂Linux驱动，但知识点零散<br>面对企业高要求，求职全程心虚，不敢投递心仪岗位</p></div><div class="jobs"><b>企业高薪BSP岗位清单</b><p>• Linux驱动工程师　　• BSP开发工程师<br>• 系统架构师　　　　• 内核开发专家<br>• 内核开发专业　　　• …</p></div></header>
  <h3 class="support">韦东山亲带+全程技术支持</h3>
  <section class="timeline"><div class="line"></div><article v-for="(stage,index) in stages" :key="stage.title"><span class="node"><component :is="stage.icon"/></span><span class="dot"></span><h4>🔥{{ stage.title }}</h4><b>{{stage.tag}}</b><ul><li v-for="item in stage.items" :key="item">{{item}}</li></ul></article></section>
  <footer><section><h4>承诺</h4><b>具备独立的Linux驱动/BSP开发能力！</b><p>我有17年嵌入式实战教学经验，这套路线完全对标企业高要求，把零散的知识点变成能落地的实战能力！<br>我全程盯着、带着、帮着你，只要你跟着执行，你不仅能吃透u-boot/驱动/内核/系统构建，更能带着实打实的项目经验去面试！</p></section><section><h4>总结</h4><ol><li><b>核心优势：</b>拒绝零散学习，26周分阶段拆解企业BSP岗核心要求；</li><li><b>实战导向：</b>不依赖录播课，以“移植、编写、构建”等实操任务为主；</li><li><b>结果保障：</b>从“略懂驱动、求职心虚”到掌握原厂级驱动开发能力。</li></ol></section></footer>
</div></template>
<style scoped>
.route-c-shell{position:relative;width:100%;min-height:900px;height:clamp(900px,65vw,1080px);aspect-ratio:auto;padding:1.8%;overflow:hidden;color:#080b10;background:#fff;font-family:Arial,"Microsoft YaHei",sans-serif}.intro{height:22%;display:grid;grid-template-columns:27% 33% 30%;justify-content:center;gap:2%}.person{position:relative;display:grid;place-items:center;font-size:100px}.person span{position:absolute;bottom:0;font-size:clamp(16px,1.35vw,24px);font-weight:700}.pain,.jobs{align-self:center;padding:8px 14px;border:2px solid #59617a;border-radius:20px;background:#f1f3fa;font-size:clamp(17px,1.3vw,24px);line-height:1.45}.pain b,.jobs b{font-size:clamp(17px,1.35vw,24px)}.pain p,.jobs p{margin:5px 0}.support{position:absolute;z-index:3;top:23%;left:37%;margin:0;padding:8px 35px;color:white;background:linear-gradient(90deg,#448ddd,#8661ce);border-radius:18px;font-size:clamp(20px,1.8vw,32px)}.timeline{position:absolute;top:26%;right:1.5%;left:1.5%;height:45%;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:2%}.line{position:absolute;top:20%;right:0;left:0;height:14px;background:#4c8ee1}.line::after{position:absolute;right:-2px;top:-14px;content:"";border-left:45px solid #4c8ee1;border-top:21px solid transparent;border-bottom:21px solid transparent}.timeline article{position:relative;min-width:0;padding-top:19%;text-align:center}.node{position:relative;z-index:2;width:clamp(80px,7vw,112px);height:clamp(80px,7vw,112px);margin:0 auto 18px;display:grid;place-items:center;color:#344c71;background:#fff;border:7px solid transparent;border-radius:50%;background-image:linear-gradient(#fff,#fff),linear-gradient(135deg,#4b95e5,#8860cd);background-origin:border-box;background-clip:padding-box,border-box}.node svg{width:62px;height:62px}.dot{display:none}.timeline article h4{margin:0;font-size:clamp(15px,1.2vw,22px);line-height:1.2}.timeline article>b{display:block;min-height:48px;font-size:clamp(15px,1.1vw,20px)}.timeline ul{margin:4px 0;padding-left:25px;text-align:left;font-size:clamp(14px,1.05vw,18px);line-height:1.45}.route-c-shell footer{position:absolute;right:3%;bottom:2%;left:3%;height:27%;display:grid;grid-template-columns:1fr 1fr;background:#eef2fa;border:2px solid #9aacbf;border-radius:18px}.route-c-shell footer section{position:relative;padding:52px 25px 12px;font-size:clamp(14px,1.05vw,19px);line-height:1.45}.route-c-shell footer section+section{border-left:2px solid #9aacbf}.route-c-shell footer h4{position:absolute;top:0;left:0;margin:0;padding:5px 65px;color:#fff;background:linear-gradient(90deg,#4e91ee,#7959c4);font-size:clamp(20px,1.8vw,32px)}.route-c-shell footer p{margin:12px 0}.route-c-shell footer ol{margin:0;padding-left:25px}
@media(max-width:1100px){.route-c-shell{min-height:0;height:auto;aspect-ratio:auto;overflow:visible}.intro{height:auto;display:grid;grid-template-columns:1fr 1fr}.person{grid-column:1/-1;height:150px}.person span{bottom:0}.support{position:relative;inset:auto;width:max-content;max-width:100%;margin:20px auto}.timeline{position:relative;inset:auto;height:auto;grid-template-columns:1fr 1fr}.line{display:none}.timeline article{padding:10px;border:2px solid #7298cf;border-radius:14px}.node{width:82px;height:82px;margin-bottom:8px}.dot{display:none}.route-c-shell footer{position:relative;inset:auto;height:auto;margin-top:58px;grid-template-columns:1fr}.route-c-shell footer section+section{border-left:0;border-top:2px solid #9aacbf}}
@media(max-width:600px){.intro,.timeline{grid-template-columns:1fr}.person{font-size:90px}.pain,.jobs{font-size:13px}.route-c-shell footer section{padding-inline:14px}.support{font-size:18px}.route-c-shell footer{margin-top:140px}}
.route-c-shell footer h4{width:210px;max-width:70%;padding:5px 18px;text-align:center}
.route-c-shell footer section+section h4{transform:translateX(-50%)}
@media(max-width:1100px){.route-c-shell footer h4,.route-c-shell footer section+section h4{left:50%;transform:translateX(-50%)}}
</style>
